# ----------------------- #
#      Main Configs       #
# ----------------------- #

author: Johannes Holmberg
email: johannes@holmberg.io
environment: development

# ------------ #
#    Jekyll    #
# ------------ #

source: source
destination: _site
plugins_dir: plugins
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "book"

exclude: [
  "assets/css/*.scss",
  "assets/js/source",
  "assets/icons"
]

# ------------- #
#    Plugins    #
# ------------- #

compress_html:
  ignore:
    envs: [development]


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

google_analytics: UA-20488297-7
